---
title: "Version control with Git practice"
author: "Dr. Kim Dill-McFarland, U. of British Columbia"
subtitle: "Experiential Data science for Undergraduate Cross-disciplinary Education"
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
  pdf_document:
    toc: yes
editor_options: 
  chunk_output_type: console
urlcolor: blue
---
# Version control with Git practice
These problems are designed to help you practice concepts and functions covered in the 'Version control with Git tutorial'.

## Learning objectives

* Practice Unix command line
* Enact version control on a text file using Git command line tools

## Practice

1. Version control a file
    - Create a new Git repo somewhere on you computer. Then, create a text file within that repo and add/commit it to version control. Next, delete that text file and add/commit this change to the repo.
    - Note the messages Git outputs in the terminal as you complete each step. They are very informative and helpful!
    - How is a file deletion noted in the log? 
    - How would you recover your text file using git commands to go back to an old version?

2. Resolve a merge conflict
    - Create another text file in your repo from #1. Add some text to the file and add/commit it. Then, create a new branch, change the text in the file, and add/commit to the branch.
    - Will you be able to merge this branch with the main repo? If so, how? If not, why not?
    - Try it and see! If there is a merge conflict, resolve it and add/commit your final file version. Check the log to see all the steps you've completed!

***