---
output: html_document
---
# Introduction to data science
- Defines data science
- Describes several uses and motivations for data science in the life sciences

***

# Command line
### Introduction to the Unix environment
- Introduces the Unix command line and basic functions like pwd, cd, ls, cp, mv...
- Applies skills to BLAST and Git

***

# R/RStudio
### Introduction to R
- Introduces the R/RStudio program
- Covers tabular data import and basic exploration
- Includes creation of base R plots

### Data manipulation and visualization in R
- Employs the tidyverse packages to manipulate, clean, and create figures from tabular data

### Intermediate data visualization in R
- Utilizes data generated by students in laboratory courses and applies additional R packages, as needed
- Customized for a given course

*** 

# Statistics
### Introduction to statistics
- Introduces the Central Limit Theorem, p-hacking, and statistical tests relevant to the course material
- Builds from t-tests to ANOVA to linear regression

### Statistics in R
- Applies statistical tests in R/RStudio
- Includes data input, test completion, and interpretation of R outputs
- Can utilize data generated by students in the course or our standard Saanich Inlet dataset

*** 

# Capstone projects
### Metagenomics analysis team project
- Focuses on pipeline construction and biological interpretation of metagenomic sequence data from microbiomes

### Microbiome analysis team project
- Focuses on biological interpretation of amplicon sequence data from microbiomes