---
title: "About Course Compiler"
output: html_document
---
Course Compiler allows you to access all of EDUCE's data science modules for teaching or self-learning purposes. Simply select the course(s) that fit your interests and have the Course Compiler Shiny App create all the materials that you will need including slides, notes, exercises, and source code.

## Online
For novice R users or those wishing to use our [example data set](about_data.html), deploy the Course Compiler from this site, select your courses, and download the resulting materials. The PDF and HTML formats provide you with all of the final files while the ZIP format also provides the source code in Rmarkdown.

## Locally
More experienced R users can download the Course Compiler app and run it locally on their machine. To obtain the app:

1) Go to the [Course Compiler](https://github.com/EDUCE-UBC/EDUCE-UBC.github.io/tree/master/Downloadable_Apps) app folder in our public Github repo.
2) Copy the link and paste it at [Gitzip](https://kinolien.github.io/gitzip/) (Top right corner beside the key icon) to download.
3) Open the app.R file in [RStudio](https://www.rstudio.com/products/rstudio/download/).
4) Click the "Run App" button or type "shiny::runApp()" in the console to launch the app.
    - You may need to install the `shiny` package.

## Customization
Running the app locally will also allow you to customize the materials with your data or content. You can modify the existing Rmarkdown files or add your own by placing them in the "Rmd_Input" directory.

Alternatively, if you would like to manually add courses or customize your Rmd, you can select the ZIP format in the app, add your own Rmd files to "Rmd_Input"", and edit the Rmd_Master_File.

***

Original build: Jonah Lin  
Updates: Kim Dill-McFarland  
Contact: info.educe@ubc.ca