---
title: "EDUCE FAQ"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
---

# What is EDUCE?

Experiential Data Science for Undergraduate Cross-disciplinary Education (EDUCE)

EDUCE seeks to develop a uniform experiential learning framework that is cross-disciplinary and collaborative to equip undergraduate students in the life sciences with basic competency and literacy in data science as it pertains to microbiome sequence information. To achieve this, EDUCE will develop and implement a mechanism to augment undergraduate training in the Department of Microbiology & Immunology (MICB) with basic analyses and statistical principles and microbiome data processing and interpretation skills that transcend any one course in the department.

# What is Course Compiler?

Here you can select and compile all the data science modules for either teaching purposes and/or self-learning purposes. Select the courses that best fit your interests/curriculum and have the Course Compiler Shiny App knit it for you. We will also provide the source code for generating the arbitrary knitted files and enable you to customize courses with your own files. More experienced data science instructors will have access to more functions, so we encourage you to learn the basics of RStudio.

For better performance, veteran instructors can download the app and run it locally on their machine (Requires RStudio): 

1) Go to the [Course Compiler](https://github.com/EDUCE-UBC/EDUCE-UBC.github.io/tree/master/Downloadable_Apps) app folder in our public repo on Github.

2) Copy the link and paste it at [Gitzip](https://kinolien.github.io/gitzip/) (Top right corner beside the key icon) to download.

3) Open the app.R file in RStudio.

4) Click the "Run App" button or type "shiny::runApp()" in the console to launch the app.

### What Course Compiler Offers
- Ability to select and knit courses that interest you and/or fit your teaching plans.
- Ability to select the HTML format for novice data science instructors or the ZIP format for more experienced data science instructors (Source code will be provided in the ZIP format for you to use and personalize your own courses).
- More experienced data science instructors will have access to knitted files that contain a table of content.

### Provided Files in ZIP Format

  - Rmd_Output = All the courses that you selected.
  - Rmd_Master_File = Master file containing R children for all the knitted courses.
  - User_File = Source code used to generate all the courses that you want.

### How do I create courses with my own Rmd files?

To create courses with your own Rmd files:

1) Select the courses offered by EDUCE in Course Compiler.
2) Select the ZIP format for download. 
3) After downloading, extract the files/folders.
4) Put all the files that you want to knit into the folder "Rmd_Output".
5) Knit the "User_File.Rmd", which will generate a "Rmd_Master_File.Rmd" that contains all the R children of the files.

# What is Data Manipulator?

The Data Manipulator Shiny App has two functionalities:

- Provide a user-friendly way to create data plots given an input file.
- Provide an interactive way to learn the various methods of normalization in a tabular and graphical way.
    - Users will be able to use either OTU/ASV count files as inputs for normalization.
    - Users will be able to normalize the data via PRA/RS, view the most abundant OTU/ASV, and download a copy of the normalized data as text files.

Novice data science instructors will be provided some basic files from Github to experiment with and more experienced data science instructors will have the ability to use their own files to do some more in-depth experimentation and manipulation of data via the graph inputs (Number of OTU/ASV to Display, Number of Columns to Display, and Random Generator Seed). The Shiny app will also allow users to download the normalized data as text files (Note: Only Percent Relative Abundance and Random Subsampling are in the app due to computation limitations).

For better performance, veteran instructors can download the app and run it locally on their machine (Requires RStudio): 

1) Go to the [Data Manipulator](https://github.com/EDUCE-UBC/EDUCE-UBC.github.io/tree/master/Downloadable_Apps) app folder in our public repo on Github.

2) Copy the link and paste it at [Gitzip](https://kinolien.github.io/gitzip/) (Top right corner beside the key icon) to download.

3) Open the app.R file in RStudio.

4) Click the "Run App" button or type "shiny::runApp()" in the console to launch the app.

### File Inputs For Data Manipulator
- Data Plotter:
    - Metadata (Txt File)
- Data Normalization:
    - OTU Count (Txt File)
    - ASV Count (Txt File)

### Purpose of "Validate Data"?

More experienced data science instructors may help us test the Data Normalization section of the Shiny app version (Random Subsampling Section) by providing us with their OTU/ASV files for integration testing. To submit your file(s), upload your file and press the "Validate Data" button. Assuming the files are valid and in the correct format, this will save a copy of your file on our server and we may use it for future tests.

# Data Normalization

Data normalization is the process of transforming/standardizing data to a common scale for comparison [4]. This is especially useful for microbial ecology since the data may come from different samples and a way to compare the trends of data on a standardized scale will be useful for further analysis [5].

## Percent Relative Abundance

Percent Relative Abundance is a technique that transforms the data into percentages, which is then used to compare how the data is relative to one another. Also known as Relative Species Abundance in microbial ecology, it is a measure of how common a species is relative to other species in a defined location [6].

This technique first identifies the total number of observations represented in each group, then each data point is divided by the total number of observations calculated earlier. The sum of all the percentages in each group should equal 100% [7].

#### Potential Benefits:
- Can easily conceptualize data without overthinking [8]: Dealing with percentages vs. actual numbers without context.
- Easy to transform data:
    - [Number of observations for each data point] / [Total number of observations for each group of data points]

#### Potential Drawbacks:
- Difficult to comprehend complex datasets [8]. This can potentially be resolved by dividing large datasets into interval classes for better visualization.

## Random Subsampling

Random Subsampling is technique that splits the data into subsets [9]. Also known as rarefaction in microbial ecology, it is a technique used to determine species richness of samples that differ in area, volume, or sampling efforts [10].

#### Potential Benefits:
- Subsetting of samples can be repeated an indefinite number of times.
- Rarefaction compares observed richness among samples for a given level of sampling effort and does not attempt to estimate true richness of community [11]:
Number of observations for each subsampled data point Total number of observations for each group of subsampled data points

#### Potential Drawbacks:
- Rarefied counts remain over-dispersed relative to Poisson model (Implies an increase in Type I error). More difficult to estimate overdispersion after rarefying due to lost information [12].
- Rarefied counts represent only a small fraction of original data (Can lead to increased chance of Type II error). Often caused by samples being discarded and poorly distinguishable samples due to discarded fraction of original library [12].
- Random step in rarefying is unnecessary and adds artificial uncertainty [12].
- Many assumptions are required if rarefaction is used for comparing samples: Sufficient sampling, comparable sampling methods, taxonomic similarity, closed communities of discrete individuals, random placement, and independent random sampling [13, 14]. 

## Multiple Imputation 
Multiple Imputation is a statistical technique that is useful for analyzing incomplete or missing data via 3 steps [15, 16]: 

1) Imputation: Missing entries of datasets are filled in m times, which can contain different values for each missing entry (m Complete datasets). 
2) Analysis: The m completed datasets are then analyzed (m Analyses). 
3) Pooling: The m analysis results are then pooled together into a final result. The MICE Package was used in R with Predictive Mean Matching (PMM) as the imputation method (A list of imputation methods can also be found here) [17]. 

#### Potential Benefits: 
- When Multiple Imputation is used correctly [18, 19, 20, 21, 22]: 
    - Reduced bias: Analysis can be done on a "complete" dataset via filling missing values with imputation methods. 
    - Improve validity: Valid inferences are obtained from the distribution average of missing data. 
    - Increase precision: Many missing data, which can potentially happen in microbial ecology due to the potential of excess zeros being missing data, may lead to the exclusion of a substantial proportion of the original sample, leading to a decrease in precision during analysis. 
    - Result in robust statistics (Resistant to outliers): Imputed values often uses the mean, median, or other statistic to impute the missing values. 
- Useful for analyzing qPCR data, which often have moderate levels of missing values [20]. 

#### Potential Drawbacks: 
- Must make a few required statistical assumptions [23]: 
    - Is the data is missing at random? 
    - Is this a multivariate normal distribution? (Needed for some of the modeling methods) 
- Need to transform variables to approximate normal distribution before running imputation procedure if data isn't normally distributed [18]. 
- Incorrect model choices or exclusion of vital data points may lead to more bias [18].

## Variance Stabilizing Transformation 
Variance Stabilizing Transformation is a technique that uses a function f to apply values to x in a dataset to create y = f(x) such that the variability of values y is not related to their mean value (Or has a constant variance) [24]. 

#### Potential Benefits: 
- Usage of DESeq2 overcomes the issue of strong variance of logarithmic fold change (LFC) estimates for genes with low read count in analysis of high-throughput sequencing data [25]: 
  - Shrinks LFC estimates toward zero when shrinkage is stronger when available information or gene is low, which could be due to low counts, high dispersion, or few degrees of freedom. 
  - Prevents the spreading apart of data for genes with low counts, where random noise is likely to dominate any biologically meaningful signal (Stabilizes variances). 
- DeSeq2's heuristics can deal with flagged outliers in two possible ways to help avoid Type I errors [25]: 
  - Outliers in conditions with six or fewer replicates cause whole gene to be flagged and removed from subsequent analysis (Includes P value adjustment for multiple testing). 
  - Outliers in conditions with seven or more replicates replaces the outlier counts with imputed value (Trimmed mean over all samples), scaled by size factor, and then re-estimates dispersion, LFCs, and P values for these genes. 
- Can consistently perform over large range of data types and is applicable for small studies with few replicates or large observational studies [25]. 

#### Potential Drawbacks: 
- Many rare species are ignored completely due to the negative values from log-like transformations being set to 0. Since DESeq was developed mainly for use with Euclidean metrics (Negative results are not a problem), this may yield misleading results for ecologically useful non-Euclidean measures [26]. 
- Many not be appropriate for highly diverse microbial environments since DESeq assumes that most microbes are not differentially abundance and for the few that are, there is an approximately balanced amount of increased/decreased abundance [26].

## References
[1] Holmes R. Software Testing. https://github.com/ubccpsc/310/blob/2017jan/readings/Testing.md (2018).

[2] Anonymous. Big Bang Integration Testing. http://www.professionalqa.com/big-bang-integration-testing (2018).

[3] Easterbrook S. Testing Strategies. http://www.cs.toronto.edu/~sme/CSC302/notes/17-Testing2.pdf (2018).

[4] Borgatti S. http://www.analytictech.com/ba762/handouts/normalization.htm (2018).

[5] Daniel Aguirre de Cárcer, Denman SE, McSweeney C, Morrison M. Evaluation of Subsampling-Based Normalization Strategies for Tagged High-Throughput Sequencing Data Sets from Gut Microbiomes. Applied and Environmental Microbiology. 2011; 77: 8795-8798.

[6] Socratic. How do species richness and relative abundance of species affect species diversity? https://socratic.org/questions/how-do-species-richness-and-relative-abundance-of-species-affect-species-diversi (2018).

[7] Percentage Frequency Distribution. Encyclopedia of Survey Research Methods. 2008.

[8] Reid A. Advantages & Disadvantages of a Frequency Table. https://sciencing.com/advantages-disadvantages-frequency-table-12000027.html (2018).

[9] Dieterle F. Random Subsampling. http://www.frank-dieterle.com/phd/2_4_3.html (2018).

[10] Chiarucci A, Bacaro G, Rocchini D, Ricotta C, Palmer MW, Scheiner SM. Spatially constrained rarefaction: incorporating the autocorrelated structure of biological communities into sample-based rarefaction. Community Ecology. 2009; 10: 209-214.

[11] Hughes JB, Hellmann JJ. The application of rarefaction techniques to molecular inventories of microbial diversity. In: Vol 397. United States: Elsevier Science & Technology; 2005: 292-308.

[12] McMurdie PJ, Holmes S. Waste not, want not: why rarefying microbiome data is inadmissible. PLoS Computational Biology. 2014; 2013; 10: e1003531.

[13] Gotelli, NJ, Colwell RK. Estimating species richness. Frontiers in Measuring Biodiversity. 2011; 12: 39-54.

[14] Tipper JC. Rarefaction and Rarefiction; The Use and Abuse of a Method in Paleoecology. Paleobiology. 1979; 5: 423-434.

[15] van Buuren S. Multiple Imputation. http://www.stefvanbuuren.nl/mi/mi.html (2018).

[16] Maldonado, A. D.; Aguilera, P. A.; and Salmeron, A. An Experimental Comparison of Methods to Handle Missing Values in Environmental Datasets. International Congress on Environmental Modelling and Software. 2016: 3.

[17] van Buuren S. MICE. https://www.rdocumentation.org/packages/mice/versions/2.25/topics/mice (2018).

[18] Anonymous. Statistics How To. http://www.statisticshowto.com/multiple-imputation/ (2018).

[19] Sterne JAC, White IR, Carlin JB, et al. Multiple imputation for missing data in epidemiological and clinical research: potential and pitfalls. BMJ. 2009; 338: 157-160.

[20] Kanwar N, Scott HM, Norby B, et al. Impact of treatment strategies on cephalosporin and tetracycline resistance gene quantities in the bovine fecal metagenome. Scientific Reports. 2014; 2015; 4: 5100.

[21] Xu L, Paterson AD, Turpin W, Xu W. Assessment and Selection of Competing Models for Zero-Inflated Microbiome Data. PLoS One. 2015; 10: e0129606.

[22] Kaul A, Mandal S, Davidov O, Peddada SD. Analysis of Microbiome Data in the Presence of Excess Zeros. Frontiers in Microbiology. 2017; 8: 2114.

[23] Quora. How do you handle missing data (statistics)? What imputation techniques do you recommend or follow? https://www.quora.com/How-do-you-handle-missing-data-statistics-What-imputation-techniques-do-you-recommend-or-follow (2018).

[24] NC State University. Nonlinear Statistical Models for Univariate and Multivariate Response. https://www.stat.ncsu.edu/people/bloomfield/courses/ST762/slides/MD-02-2.pdf (2018).

[25] Love MI, Huber W, Anders S. Moderated estimation of fold change and dispersion for RNA-seq data with DESeq2. Genome biology. 2014; 15: 550-550.

[26] Weiss S, Xu ZZ, Peddada S, et al. Normalization and microbial differential abundance strategies depend upon data characteristics. Microbiome. 2017; 5: 27.