---
title: "Introduction to command line"
---
The command line / terminal / shell allows you to access a computer using only a text-based window. It is a foundational tool in data science and is used throughout many EDUCE modules.

Here, you will find guided video tutorials covering some basic command line functions and application of these functions using the Basic Local Alignment Search Tool ([BLAST](https://blast.ncbi.nlm.nih.gov/Blast.cgi)).

## Moving about your computer
Learn how to navigate your computer including 

- an introduction to the command line program
- pwd, print working directory
- cd, change directory
- ls, list

<iframe width="560" height="315" src="https://www.youtube.com/embed/NZ7YmgGy0uk?rel=0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

<br>
<br>

## Command line BLAST
Learn additional command line functions including

- unzip, unpack a .zip file
- head, see the first lines of a file
- tail, see the last lines of a file
- awk, subset a file (and other functionalities not covered here)
- blastn, nucleotide BLAST

<iframe width="560" height="315" src="https://www.youtube.com/embed/sU44ZtZlzo4" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

<br>
<br>

**Windows versions coming soon!**
