---
title: "Working on a server with OpenSSH"
output: html_document
---

These instructions will ensure that your local computer can connect to a Linux server and copy files between them using a suite of software tools called OpenSSH. 

(If you were looking for instructions for a local install and configuration of [`bash`](bash.html), please check the instructions for your operating system.)

## {.tabset .tabset-fade .tabset-pills}

### Windows 10

OpenSSH comes pre-installed if you have Windows 10 version 1803 or newer. (The first 2 numbers indicate in which year an update was released, and the second two numbers either the month or the half---H1 or H2---of the year. For example, version 1803 was released in March/April of 2018, or 20H2 in October 2020). In general, we advice you to [update to the latest Windows 10 version](os.html) and thus you should already have OpenSSH available to you. If your Windows 10 version is older because you cannot update then follow the [official Microsoft documentation on how to install OpenSSH Client](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse).

### macOS/Linux

OpenSSH comes already pre-installed on these operating systems, and you do not need to do anything.
