---
title: "Version control with GitHub practice"
author: "Dr. Kim Dill-McFarland, U. of British Columbia"
subtitle: "Experiential Data science for Undergraduate Cross-disciplinary Education"
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
  pdf_document:
    toc: yes
editor_options: 
  chunk_output_type: console
urlcolor: blue
---
# Version control with GitHub practice
These problems are designed to help you practice concepts and functions covered in the 'Version control with GitHub tutorial'. 

*To complete all exercises, please complete the steps in the 'GitHub tutorial' and find a partner to work with.*

## Learning objectives

* Practice Unix command line
* Share and modify a version controlled file using GitHub

## Practice

1. Create and use a GitHub repo
    - Find a directory on your computer that you wish to version control and share on GitHub. Initialize it as a repo, add/commit files within the repo, and link it to your GitHub.
    - Make changes in one or more files on your computer and push to your GitHub.
        - Which types of files can you easily see changes in? Which types is it difficult to see specific changes in? Think about how well-crafted commit messages may help with this issue!
    - Make changes in one or more files through GitHub online. 
        - How do you bring these changes to your local repo?
        - If you decide you prefer the version on your local computer, how would you force GitHub back to this version?

2. Collaborate on GitHub
    - This exercise simulates what is would be like to collaborate on the same repo with another person.
    - In pairs:
        1. UserA: Use `git clone` to copy the `TestRepo` from UserB.
        2. UserB: Make a change to `README.md` in your local repo on your own computer and `push` that change to your GitHub.
        3. UserA: Update your copy of UserB's repo.
        4. Switch roles!

***