---
title: "Base R practice"
author: "Dr. Kim Dill-McFarland, U. of British Columbia"
subtitle: "Experiential Data science for Undergraduate Cross-disciplinary Education"
output:
  html_document:
    toc: yes
    toc_float:
      collapsed: no
  pdf_document:
    toc: yes
editor_options: 
  chunk_output_type: console
urlcolor: blue
---
# Base R practice
These problems are designed to help you practice concepts and functions covered in the 'Base R tutorial'.

## Learning objectives

* Execute commands in base R to:
    * Load tabular data
    * Access columns and rows within a data frame
    * Perform basic calculations on tabular data
    * Subset a data frame

## Setup
Open a new RStudio session and create a Project. Download the data file `data.csv` using the following command in RStudio. Also, start a new R script to save you responses.

```{r}
write.csv(
  read.csv("https://raw.githubusercontent.com/EDUCE-UBC/workshop_data/master/data.csv"),
  "data.csv", row.names=FALSE)
```

Not sure what a Project is? Be sure to include the "RStudio tutorial" in your materials!

If you would like to learn more about Saanich Inlet and these data, checkout [our description](https://educe-ubc.github.io/about_data.html).

## Practice
### Load data 

1. Read in `data.csv` using one of the `read.` functions and save it as an object in RStudio named `dat`. Be sure to include any additional arguments needed to correctly format the data in R.
    - You will use these data in some of the following exercises.

### Access data
2. Use the `$` operator to access the `Season` column.
3. Access the 17th oxygen value (`O2_uM`) using `[ ]` and/or `$`.

### Basic calculations
4. Compute the natural logarithm of 4, base 2 logarithm of 4, and base 4 logarithm of 4. *Hint*: Use help `?` to find out more about the `log()` function.
5. Calculate the minimum, maximum, and mean of the `Depth_m` variable.
    
### Subset data
6. Determine what `Depth_m` value occurs in the 20th row
7. Return the cell where oxygen (`O2_uM`) equals 91.115
8. Subset the data to observations where `Depth_m` equals 120 m.

***