on:
  push:
     branches:
       - main

name: rendersite

jobs:
  site:
    name: Render-Site
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install R packages
        run: Rscript -e 'install.packages(c("rmarkdown", "downloadthis"))'
      - name: Render Book
        run: >-
          Rscript -e 'rmarkdown::render_site(encoding = "UTF-8", quiet = TRUE)'
      - uses: actions/upload-artifact@v1
        with:
          name: _site
          path: _site/
  
# Published to `gh-pages` branch
  checkout-and-deploy:
    runs-on: ubuntu-latest
    needs: site
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          # Optional artifact name
          name: _site
          # Optional destination path
          path: _site/
      - name: Deploy to GitHub Pages
        uses: Cecilapp/GitHub-Pages-deploy@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email:  ${{ secrets.EMAIL }}
          build_dir: _site
          branch: gh-pages
         