---
title: "Problem_Set_1-1"
author: "Jonah Lin (30616130)"
date: "March 18, 2018"
output: html_document
---

#### Learning Objectives: 
Describe the numerical abundance of microbial life in relation to the ecology and biogeochemistry of Earth systems.

#### Specific Questions:
* What are the primary prokaryotic habitats on Earth and how do they vary with respect to their capacity to support life? Provide a breakdown of total cell abundance for each primary habitat from the tables provided in the text.

  
    Primary Prokaryotic Habitats on Earth:  
    - Aquatic Environments = 1.2 * 10^29^ Cells  
    - Subsurface = 3.8 * 10^30^ Cells  
    - Soil = 2.6 * 10^29^ Cells

    How do they vary with respect to their capacity to support life:  
    Aquatic environments have the highest rate of cellular productivity while subsurface environments have the lowest rate of cellular productivity between the 3 habitats (Even though they have the highest population).


* What is the estimated prokaryotic cell abundance in the upper 200 m of the ocean and what fraction of this biomass is represented by marine cyanobacterium including Prochlorococcus? What is the significance of this ratio with respect to carbon cycling in the ocean and the atmospheric composition of the Earth?


    Estimated Prokaryotic Cell Abundance in Upper 200m of Ocean: 3.6 * 10^28^  
    Fraction represented by marine cyanobacterium (+ Prochlorococcus): (4 * 10^4^) / (5 * 10^5^) * 100 = 8%  
    Significance of this ratio with respect to C cycling in ocean and atmospheric composition of Earth:  
    Approx. 8% of these prokaryotes (Cyanobacteria + Prochlorococcus) are contributing to the conversion of CO~2~ to O~2~
    
    
* What is the difference between an autotroph, heterotroph, and a lithotroph based on information provided in the text?


    Difference Between Autotroph/Heterotroph/Lithotroph:
    - Autotroph = Photosynthetic, assimilate inorganic carbon (CO~2~ --> Biomass)
    - Heterotroph = Assimilate organic carbon
    - Lithotroph = Assimilate inorganic substrate  
    
    Based on information provided in text.
    
    
* Based on information provided in the text and your knowledge of geography what is the deepest habitat capable of supporting prokaryotic life? What is the primary limiting factor at this depth?  


    Deepest Habitat: 4 km (Terrestrial) and 10.9 - 14.9 km (Marine)  
    Primary Limiting Factor: Temperature (125^o^C)


* Based on information provided in the text your knowledge of geography what is the highest habitat capable of supporting prokaryotic life? What is the primary limiting factor at this height?  


    Highest Habitat: 77 km (In reality ~20 km above surface)  
    Primary Limiting Factor(s): Stable Space/Resources/Radiation/Lack of Moisture


* Based on estimates of prokaryotic habitat limitation, what is the vertical distance of the Earth's biosphere measured in km?  
    
    
    Vertical Distance of Earth's Biosphere: ~24 - 44 km  


* How was annual cellular production of prokaryotes described in Table 7 column four determined? (Provide an example of the calculation)  
    
    
    Annual Cellular Production of Prokaryotes:  
    Population * (Turnover/Yr) = Cells/Yr  
    3.6 * 10^28^ * 365 Days/16 Turnovers = 8.2 * 10^29^ Cells/Yr  
    

* What is the relationship between carbon content, carbon assimilation efficiency and turnover rates in the upper 200m of the ocean? Why does this vary with depth in the ocean and between terrestrial and marine habitats?  
    
    
    Relationship between C content, C assimilation efficiency, and turnover rates in the upper 200m of ocean:  
    Due to the high turnover rates in the upper 200m of ocean and the estimated low C assimilation efficiency (0.2), the C content will be low since the majority of C will be used to support the turnover of prokaryotes and not assimilated.  
    This varies with depth in ocean and between terrestrial and marine habitats because as the depth increases, the turnover rate decreases due to low metabolic activity. This in turn leads to higher C contents since the turnover of prokaryotes in deeper depths becomes low enough for C to become assimilated.  
    


* How were the frequency numbers for four simultaneous mutations in shared genes determined for marine heterotrophs and marine autotrophs given an average mutation rate of 4 x 10^-7^ per DNA replication? (Provide an example of the calculation with units. Hint: cell and generation cancel out)  
    
    
    Frequency Number for 4 Simultaneous Mutations in Shared Genes:  
    Average Mutation Rate = 4 * 10^-7^ Per DNA Replication
    365 / 16 = 22.8 Turnovers/Yr   
    (4 * 10^-7^)^4^ = 2.56 * 10^-26^ Mutations/Generation  
    3.6 * 10^28^ Cells * 22.8 = 8.2 * 10^29^ Cells/Yr * 2.56 * 10^-26^ Mutatations/Generation = 2.1 * 10^4^ Mutations/Yr


* Given the large population size and high mutation rate of prokaryotic cells, what are the implications with respect to genetic diversity and adaptive potential? Are point mutations the only way in which microbial genomes diversify and adapt?  
    
    
    Implications:
    - Higher genetic diversity due to high mutation rate 
    - Higher adaptive potential to environment due to high mutation rate (Natural selection of prokaryotic cells - Favours ones that contain mutation to help with survival)  
    
    No: Point mutations are not the only way in which microbial genomes diversify and adapt. There can also be HGT between other bacteria, different levels of gene regulation/expression, insertions/deletions, etc.  
    

* What relationships can be inferred between prokaryotic abundance, diversity, and metabolic potential based on the information provided in the text?
    
    
    Relationships Between Prokaryotic Abundance, Diversity, and Metabolic Potential:
    High Prokaryotic Abundance <--> Higher Diversity <--> Higher Metabolic Potentials (More prokaryotes will lead to higher diversity via mutations and mutations could contribute to better genes that help with metabolism)  